### ISSUE TITLE
add defineTx on tx helper

### ISSUE THREAD

**Issue by PatDB** [LiskFrance/lisk-transparency-reports#37]
function that save the tx's type on myreport page

**Comment by SherlockStd** [comment]
hum there is no tx helper yet
better open an issue for tx helper wit all functions needed inside this issue under this form:
- [ ] 
- [ ] 
- [ ]

**Comment by PatDB** [comment]
there are on my local version ...like you wrote to me i must pull when closed them (Github workflow protocol).... 
you have say to me to write what i'm working on..

**Comment by SherlockStd** [comment]
yep but don't open too specifics issues, check the others issues you'll see
