### ISSUE TITLE
creation oh transactions routing

### ISSUE THREAD

**Issue by PatDB** [LiskFrance/lisk-transparency-reports#41]
-apiRoutes.use('/listTX', txRoutes):
 json to list txtype

-txRoutes.post('/defineTX',requireAuth, TxHelper.defineTx):
  save type transaction on myreport

-txRoutes.get('/TxbyDelegate', requireAuth, TxHelper.TxByDelegate)
  list transactions  by delegate on myreport

-txRoutes.get('/filterTxByType', requireAuth, TxHelper.filterTxByType)
 list transactions on myrepot by user/type

-txRoutes.get('/MyByAddresses', requireAuth, TxHelper.MyByAddresses)
  list/filter transactions by address on myreport

**Comment by SherlockStd** [comment]
Moved into #38
